// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/nicholas-fedor/shoutrrr/internal/failures"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFailure creates a new instance of MockFailure. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFailure(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFailure {
	mock := &MockFailure{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFailure is an autogenerated mock type for the Failure type
type MockFailure struct {
	mock.Mock
}

type MockFailure_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFailure) EXPECT() *MockFailure_Expecter {
	return &MockFailure_Expecter{mock: &_m.Mock}
}

// Error provides a mock function for the type MockFailure
func (_mock *MockFailure) Error() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Error")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockFailure_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type MockFailure_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
func (_e *MockFailure_Expecter) Error() *MockFailure_Error_Call {
	return &MockFailure_Error_Call{Call: _e.mock.On("Error")}
}

func (_c *MockFailure_Error_Call) Run(run func()) *MockFailure_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFailure_Error_Call) Return(s string) *MockFailure_Error_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockFailure_Error_Call) RunAndReturn(run func() string) *MockFailure_Error_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockFailure
func (_mock *MockFailure) ID() failures.FailureID {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 failures.FailureID
	if returnFunc, ok := ret.Get(0).(func() failures.FailureID); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(failures.FailureID)
	}
	return r0
}

// MockFailure_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockFailure_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockFailure_Expecter) ID() *MockFailure_ID_Call {
	return &MockFailure_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockFailure_ID_Call) Run(run func()) *MockFailure_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFailure_ID_Call) Return(failureID failures.FailureID) *MockFailure_ID_Call {
	_c.Call.Return(failureID)
	return _c
}

func (_c *MockFailure_ID_Call) RunAndReturn(run func() failures.FailureID) *MockFailure_ID_Call {
	_c.Call.Return(run)
	return _c
}

// Is provides a mock function for the type MockFailure
func (_mock *MockFailure) Is(target error) bool {
	ret := _mock.Called(target)

	if len(ret) == 0 {
		panic("no return value specified for Is")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(error) bool); ok {
		r0 = returnFunc(target)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockFailure_Is_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Is'
type MockFailure_Is_Call struct {
	*mock.Call
}

// Is is a helper method to define mock.On call
//   - target error
func (_e *MockFailure_Expecter) Is(target interface{}) *MockFailure_Is_Call {
	return &MockFailure_Is_Call{Call: _e.mock.On("Is", target)}
}

func (_c *MockFailure_Is_Call) Run(run func(target error)) *MockFailure_Is_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 error
		if args[0] != nil {
			arg0 = args[0].(error)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFailure_Is_Call) Return(b bool) *MockFailure_Is_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockFailure_Is_Call) RunAndReturn(run func(target error) bool) *MockFailure_Is_Call {
	_c.Call.Return(run)
	return _c
}

// Unwrap provides a mock function for the type MockFailure
func (_mock *MockFailure) Unwrap() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Unwrap")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFailure_Unwrap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unwrap'
type MockFailure_Unwrap_Call struct {
	*mock.Call
}

// Unwrap is a helper method to define mock.On call
func (_e *MockFailure_Expecter) Unwrap() *MockFailure_Unwrap_Call {
	return &MockFailure_Unwrap_Call{Call: _e.mock.On("Unwrap")}
}

func (_c *MockFailure_Unwrap_Call) Run(run func()) *MockFailure_Unwrap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFailure_Unwrap_Call) Return(err error) *MockFailure_Unwrap_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFailure_Unwrap_Call) RunAndReturn(run func() error) *MockFailure_Unwrap_Call {
	_c.Call.Return(run)
	return _c
}
