// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/nicholas-fedor/shoutrrr/pkg/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockContextAttachmentSender creates a new instance of MockContextAttachmentSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockContextAttachmentSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockContextAttachmentSender {
	mock := &MockContextAttachmentSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockContextAttachmentSender is an autogenerated mock type for the ContextAttachmentSender type
type MockContextAttachmentSender struct {
	mock.Mock
}

type MockContextAttachmentSender_Expecter struct {
	mock *mock.Mock
}

func (_m *MockContextAttachmentSender) EXPECT() *MockContextAttachmentSender_Expecter {
	return &MockContextAttachmentSender_Expecter{mock: &_m.Mock}
}

// SendItemsContext provides a mock function for the type MockContextAttachmentSender
func (_mock *MockContextAttachmentSender) SendItemsContext(ctx context.Context, items []types.MessageItem, params types.Params) error {
	ret := _mock.Called(ctx, items, params)

	if len(ret) == 0 {
		panic("no return value specified for SendItemsContext")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []types.MessageItem, types.Params) error); ok {
		r0 = returnFunc(ctx, items, params)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContextAttachmentSender_SendItemsContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendItemsContext'
type MockContextAttachmentSender_SendItemsContext_Call struct {
	*mock.Call
}

// SendItemsContext is a helper method to define mock.On call
//   - ctx context.Context
//   - items []types.MessageItem
//   - params types.Params
func (_e *MockContextAttachmentSender_Expecter) SendItemsContext(ctx any, items any, params any) *MockContextAttachmentSender_SendItemsContext_Call {
	return &MockContextAttachmentSender_SendItemsContext_Call{Call: _e.mock.On("SendItemsContext", ctx, items, params)}
}

func (_c *MockContextAttachmentSender_SendItemsContext_Call) Run(run func(ctx context.Context, items []types.MessageItem, params types.Params)) *MockContextAttachmentSender_SendItemsContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []types.MessageItem
		if args[1] != nil {
			arg1 = args[1].([]types.MessageItem)
		}
		var arg2 types.Params
		if args[2] != nil {
			arg2 = args[2].(types.Params)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockContextAttachmentSender_SendItemsContext_Call) Return(err error) *MockContextAttachmentSender_SendItemsContext_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContextAttachmentSender_SendItemsContext_Call) RunAndReturn(run func(ctx context.Context, items []types.MessageItem, params types.Params) error) *MockContextAttachmentSender_SendItemsContext_Call {
	_c.Call.Return(run)
	return _c
}
