// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/nicholas-fedor/shoutrrr/pkg/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockContextSender creates a new instance of MockContextSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockContextSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockContextSender {
	mock := &MockContextSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockContextSender is an autogenerated mock type for the ContextSender type
type MockContextSender struct {
	mock.Mock
}

type MockContextSender_Expecter struct {
	mock *mock.Mock
}

func (_m *MockContextSender) EXPECT() *MockContextSender_Expecter {
	return &MockContextSender_Expecter{mock: &_m.Mock}
}

// SendContext provides a mock function for the type MockContextSender
func (_mock *MockContextSender) SendContext(ctx context.Context, message string, params *types.Params) error {
	ret := _mock.Called(ctx, message, params)

	if len(ret) == 0 {
		panic("no return value specified for SendContext")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *types.Params) error); ok {
		r0 = returnFunc(ctx, message, params)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContextSender_SendContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendContext'
type MockContextSender_SendContext_Call struct {
	*mock.Call
}

// SendContext is a helper method to define mock.On call
//   - ctx context.Context
//   - message string
//   - params *types.Params
func (_e *MockContextSender_Expecter) SendContext(ctx any, message any, params any) *MockContextSender_SendContext_Call {
	return &MockContextSender_SendContext_Call{Call: _e.mock.On("SendContext", ctx, message, params)}
}

func (_c *MockContextSender_SendContext_Call) Run(run func(ctx context.Context, message string, params *types.Params)) *MockContextSender_SendContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *types.Params
		if args[2] != nil {
			arg2 = args[2].(*types.Params)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockContextSender_SendContext_Call) Return(err error) *MockContextSender_SendContext_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContextSender_SendContext_Call) RunAndReturn(run func(ctx context.Context, message string, params *types.Params) error) *MockContextSender_SendContext_Call {
	_c.Call.Return(run)
	return _c
}
