// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/nicholas-fedor/shoutrrr/pkg/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockHTTPClientSetter creates a new instance of MockHTTPClientSetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHTTPClientSetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHTTPClientSetter {
	mock := &MockHTTPClientSetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHTTPClientSetter is an autogenerated mock type for the HTTPClientSetter type
type MockHTTPClientSetter struct {
	mock.Mock
}

type MockHTTPClientSetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHTTPClientSetter) EXPECT() *MockHTTPClientSetter_Expecter {
	return &MockHTTPClientSetter_Expecter{mock: &_m.Mock}
}

// SetHTTPClient provides a mock function for the type MockHTTPClientSetter
func (_mock *MockHTTPClientSetter) SetHTTPClient(client types.HTTPClient) {
	_mock.Called(client)
	return
}

// MockHTTPClientSetter_SetHTTPClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHTTPClient'
type MockHTTPClientSetter_SetHTTPClient_Call struct {
	*mock.Call
}

// SetHTTPClient is a helper method to define mock.On call
//   - client types.HTTPClient
func (_e *MockHTTPClientSetter_Expecter) SetHTTPClient(client any) *MockHTTPClientSetter_SetHTTPClient_Call {
	return &MockHTTPClientSetter_SetHTTPClient_Call{Call: _e.mock.On("SetHTTPClient", client)}
}

func (_c *MockHTTPClientSetter_SetHTTPClient_Call) Run(run func(client types.HTTPClient)) *MockHTTPClientSetter_SetHTTPClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 types.HTTPClient
		if args[0] != nil {
			arg0 = args[0].(types.HTTPClient)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHTTPClientSetter_SetHTTPClient_Call) Return() *MockHTTPClientSetter_SetHTTPClient_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHTTPClientSetter_SetHTTPClient_Call) RunAndReturn(run func(client types.HTTPClient)) *MockHTTPClientSetter_SetHTTPClient_Call {
	_c.Run(run)
	return _c
}
