// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/nicholas-fedor/shoutrrr/pkg/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSender creates a new instance of MockSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSender {
	mock := &MockSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSender is an autogenerated mock type for the Sender type
type MockSender struct {
	mock.Mock
}

type MockSender_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSender) EXPECT() *MockSender_Expecter {
	return &MockSender_Expecter{mock: &_m.Mock}
}

// Send provides a mock function for the type MockSender
func (_mock *MockSender) Send(message string, params *types.Params) error {
	ret := _mock.Called(message, params)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, *types.Params) error); ok {
		r0 = returnFunc(message, params)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSender_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockSender_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - message string
//   - params *types.Params
func (_e *MockSender_Expecter) Send(message interface{}, params interface{}) *MockSender_Send_Call {
	return &MockSender_Send_Call{Call: _e.mock.On("Send", message, params)}
}

func (_c *MockSender_Send_Call) Run(run func(message string, params *types.Params)) *MockSender_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *types.Params
		if args[1] != nil {
			arg1 = args[1].(*types.Params)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSender_Send_Call) Return(err error) *MockSender_Send_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSender_Send_Call) RunAndReturn(run func(message string, params *types.Params) error) *MockSender_Send_Call {
	_c.Call.Return(run)
	return _c
}
