// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	"github.com/nicholas-fedor/shoutrrr/pkg/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockServiceTimeout creates a new instance of MockServiceTimeout. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServiceTimeout(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServiceTimeout {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockServiceTimeout{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockServiceTimeout is an autogenerated mock type for the ServiceTimeout type
type MockServiceTimeout struct {
	mock.Mock
}

type MockServiceTimeout_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServiceTimeout) EXPECT() *MockServiceTimeout_Expecter {
	return &MockServiceTimeout_Expecter{mock: &_m.Mock}
}

// ServiceTimeout provides a mock function for the type MockServiceTimeout
func (_mock *MockServiceTimeout) ServiceTimeout(params *types.Params) time.Duration {
	ret := _mock.Called(params)

	if len(ret) == 0 {
		panic("no return value specified for ServiceTimeout")
	}

	var r0 time.Duration
	if returnFunc, ok := ret.Get(0).(func(*types.Params) time.Duration); ok {
		r0 = returnFunc(params)
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	return r0
}

// MockServiceTimeout_ServiceTimeout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServiceTimeout'
type MockServiceTimeout_ServiceTimeout_Call struct {
	*mock.Call
}

// ServiceTimeout is a helper method to define mock.On call
//   - params *types.Params
func (_e *MockServiceTimeout_Expecter) ServiceTimeout(params any) *MockServiceTimeout_ServiceTimeout_Call {
	return &MockServiceTimeout_ServiceTimeout_Call{Call: _e.mock.On("ServiceTimeout", params)}
}

func (_c *MockServiceTimeout_ServiceTimeout_Call) Run(run func(params *types.Params)) *MockServiceTimeout_ServiceTimeout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *types.Params
		if args[0] != nil {
			arg0 = args[0].(*types.Params)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServiceTimeout_ServiceTimeout_Call) Return(duration time.Duration) *MockServiceTimeout_ServiceTimeout_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *MockServiceTimeout_ServiceTimeout_Call) RunAndReturn(run func(params *types.Params) time.Duration) *MockServiceTimeout_ServiceTimeout_Call {
	_c.Call.Return(run)
	return _c
}
