name: "Checkout"
description: "Checkout repository code"

inputs:
  fetch-depth:
    description: "Number of commits to fetch"
    required: false
    default: "1"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
