name: "Checkout"
description: "Checkout repository code"

inputs:
  fetch-depth:
    description: "Number of commits to fetch"
    required: false
    default: "1"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
