// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockEavesdropper creates a new instance of MockEavesdropper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEavesdropper(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEavesdropper {
	mock := &MockEavesdropper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEavesdropper is an autogenerated mock type for the Eavesdropper type
type MockEavesdropper struct {
	mock.Mock
}

type MockEavesdropper_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEavesdropper) EXPECT() *MockEavesdropper_Expecter {
	return &MockEavesdropper_Expecter{mock: &_m.Mock}
}

// GetClientSentences provides a mock function for the type MockEavesdropper
func (_mock *MockEavesdropper) GetClientSentences() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetClientSentences")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockEavesdropper_GetClientSentences_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClientSentences'
type MockEavesdropper_GetClientSentences_Call struct {
	*mock.Call
}

// GetClientSentences is a helper method to define mock.On call
func (_e *MockEavesdropper_Expecter) GetClientSentences() *MockEavesdropper_GetClientSentences_Call {
	return &MockEavesdropper_GetClientSentences_Call{Call: _e.mock.On("GetClientSentences")}
}

func (_c *MockEavesdropper_GetClientSentences_Call) Run(run func()) *MockEavesdropper_GetClientSentences_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEavesdropper_GetClientSentences_Call) Return(strings []string) *MockEavesdropper_GetClientSentences_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockEavesdropper_GetClientSentences_Call) RunAndReturn(run func() []string) *MockEavesdropper_GetClientSentences_Call {
	_c.Call.Return(run)
	return _c
}

// GetConversation provides a mock function for the type MockEavesdropper
func (_mock *MockEavesdropper) GetConversation(includeGreeting bool) string {
	ret := _mock.Called(includeGreeting)

	if len(ret) == 0 {
		panic("no return value specified for GetConversation")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(bool) string); ok {
		r0 = returnFunc(includeGreeting)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockEavesdropper_GetConversation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConversation'
type MockEavesdropper_GetConversation_Call struct {
	*mock.Call
}

// GetConversation is a helper method to define mock.On call
//   - includeGreeting bool
func (_e *MockEavesdropper_Expecter) GetConversation(includeGreeting interface{}) *MockEavesdropper_GetConversation_Call {
	return &MockEavesdropper_GetConversation_Call{Call: _e.mock.On("GetConversation", includeGreeting)}
}

func (_c *MockEavesdropper_GetConversation_Call) Run(run func(includeGreeting bool)) *MockEavesdropper_GetConversation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEavesdropper_GetConversation_Call) Return(s string) *MockEavesdropper_GetConversation_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockEavesdropper_GetConversation_Call) RunAndReturn(run func(includeGreeting bool) string) *MockEavesdropper_GetConversation_Call {
	_c.Call.Return(run)
	return _c
}
