// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewMockMockClientService creates a new instance of MockMockClientService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMockClientService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMockClientService {
	mock := &MockMockClientService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMockClientService is an autogenerated mock type for the MockClientService type
type MockMockClientService struct {
	mock.Mock
}

type MockMockClientService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMockClientService) EXPECT() *MockMockClientService_Expecter {
	return &MockMockClientService_Expecter{mock: &_m.Mock}
}

// GetHTTPClient provides a mock function for the type MockMockClientService
func (_mock *MockMockClientService) GetHTTPClient() *http.Client {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetHTTPClient")
	}

	var r0 *http.Client
	if returnFunc, ok := ret.Get(0).(func() *http.Client); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Client)
		}
	}
	return r0
}

// MockMockClientService_GetHTTPClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHTTPClient'
type MockMockClientService_GetHTTPClient_Call struct {
	*mock.Call
}

// GetHTTPClient is a helper method to define mock.On call
func (_e *MockMockClientService_Expecter) GetHTTPClient() *MockMockClientService_GetHTTPClient_Call {
	return &MockMockClientService_GetHTTPClient_Call{Call: _e.mock.On("GetHTTPClient")}
}

func (_c *MockMockClientService_GetHTTPClient_Call) Run(run func()) *MockMockClientService_GetHTTPClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMockClientService_GetHTTPClient_Call) Return(client *http.Client) *MockMockClientService_GetHTTPClient_Call {
	_c.Call.Return(client)
	return _c
}

func (_c *MockMockClientService_GetHTTPClient_Call) RunAndReturn(run func() *http.Client) *MockMockClientService_GetHTTPClient_Call {
	_c.Call.Return(run)
	return _c
}
