name: "Golang Security Checker"
description: "Run Gosec security scanner and upload SARIF report"

runs:
  using: "composite"
  steps:
    - name: Checkout Source
      uses: ./.github/actions/checkout
    - name: Run Gosec Security Scanner
      uses: securego/gosec@f9c52aac4b897c84070cb8c8ef0c0d2d2180d532
      with:
        args: "-no-fail -fmt sarif -out results.sarif -tests ./..."
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@303c0aef88fc2fe5ff6d63d3b1596bfd83dfa1f9 # v3
      with:
        sarif_file: results.sarif
