name: "Golang Security Checker"
description: "Run Gosec security scanner and upload SARIF report"

runs:
  using: "composite"
  steps:
    - name: Checkout Source
      uses: ./.github/actions/checkout
    - name: Run Gosec Security Scanner
      uses: securego/gosec@15d5c61e866bc2e2e8389376a31f1e5e09bde7d8 # v2.22.9
      with:
        args: "-no-fail -fmt sarif -out results.sarif -tests ./..."
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@a8d1ac45b9a34d11fe398d5503176af0d06b303e # v3
      with:
        sarif_file: results.sarif
