name: "Docker Login"
description: "Login to Docker registries"

runs:
  using: "composite"
  steps:
    - name: Login to Docker Hub
      uses: docker/login-action@2e1345c05f9563db17b704b7855578af55a6c8be
      with:
        username: ${{ inputs.dockerhub-username }}
        password: ${{ inputs.dockerhub-token }}
    - name: Login to GHCR
      uses: docker/login-action@2e1345c05f9563db17b704b7855578af55a6c8be
      with:
        registry: ghcr.io
        username: ${{ inputs.ghcr-username }}
        password: ${{ inputs.ghcr-token }}

inputs:
  dockerhub-username:
    description: "Docker Hub username"
    required: true
  dockerhub-token:
    description: "Docker Hub token"
    required: true
  ghcr-username:
    description: "GHCR username"
    required: true
  ghcr-token:
    description: "GHCR token"
    required: true
