name: "govulncheck"
description: "Run govulncheck vulnerability scanner and upload SARIF report"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@faf52423ec0d44c58f68e83b614bfcd99dded66f
      with:
        go-version-file: go.mod

    - name: Install govulncheck
      shell: bash
      run: go install golang.org/x/vuln/cmd/govulncheck@latest

    - name: Checkout main branch
      if: github.event_name == 'pull_request'
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      with:
        ref: "main"
        fetch-depth: 0
        path: "main"

    - name: Run govulncheck on main
      if: github.event_name == 'pull_request'
      shell: bash
      run: |
        cd main
        govulncheck -format sarif ./... > ../main.sarif

    - name: Run govulncheck
      shell: bash
      run: |
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          govulncheck -format sarif ./... > results.sarif
        else
          govulncheck -format sarif ./... > results.sarif
        fi

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@0499de31b99561a6d14a36a5f662c2a54f91beee # v4
      with:
        sarif_file: results.sarif
