name: "govulncheck"
description: "Run govulncheck vulnerability scanner and upload SARIF report"

inputs:
  go-version:
    description: "Go version to use"
    required: false
    default: "1.25.x"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@c0137caad775660c0844396c52da96e560aba63d
      with:
        go-version: ${{ inputs.go-version }}

    - name: Install govulncheck
      shell: bash
      run: go install golang.org/x/vuln/cmd/govulncheck@latest

    - name: Checkout main branch
      if: github.event_name == 'pull_request'
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      with:
        ref: "main"
        fetch-depth: 0
        path: "main"

    - name: Run govulncheck on main
      if: github.event_name == 'pull_request'
      shell: bash
      run: |
        cd main
        govulncheck -format sarif ./... > ../main.sarif

    - name: Run govulncheck
      shell: bash
      run: |
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          govulncheck -format sarif -baseline main.sarif ./... > results.sarif
        else
          govulncheck -format sarif ./... > results.sarif
        fi

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@16140ae1a102900babc80a33c44059580f687047 # v4
      with:
        sarif_file: results.sarif
