name: "govulncheck"
description: "Run govulncheck vulnerability scanner and upload SARIF report"

inputs:
  go-version:
    description: "Go version to use"
    required: false
    default: "1.25.x"

runs:
  using: "composite"
  steps:
    - id: govulncheck
      uses: nicholas-fedor/govulncheck-action@1e9ef2cbd93abefcc8605e05f8c212aa90181f6f
      with:
        output-format: sarif
        output-file: results.sarif
        go-version-input: ${{ inputs.go-version }}
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@16140ae1a102900babc80a33c44059580f687047 # v4
      with:
        sarif_file: results.sarif
