// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewMockContextClient creates a new instance of MockContextClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockContextClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockContextClient {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockContextClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockContextClient is an autogenerated mock type for the ContextClient type
type MockContextClient struct {
	mock.Mock
}

type MockContextClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockContextClient) EXPECT() *MockContextClient_Expecter {
	return &MockContextClient_Expecter{mock: &_m.Mock}
}

// ErrorResponse provides a mock function for the type MockContextClient
func (_mock *MockContextClient) ErrorResponse(err error, response any) bool {
	ret := _mock.Called(err, response)

	if len(ret) == 0 {
		panic("no return value specified for ErrorResponse")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(error, any) bool); ok {
		r0 = returnFunc(err, response)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockContextClient_ErrorResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ErrorResponse'
type MockContextClient_ErrorResponse_Call struct {
	*mock.Call
}

// ErrorResponse is a helper method to define mock.On call
//   - err error
//   - response any
func (_e *MockContextClient_Expecter) ErrorResponse(err any, response any) *MockContextClient_ErrorResponse_Call {
	return &MockContextClient_ErrorResponse_Call{Call: _e.mock.On("ErrorResponse", err, response)}
}

func (_c *MockContextClient_ErrorResponse_Call) Run(run func(err error, response any)) *MockContextClient_ErrorResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 error
		if args[0] != nil {
			arg0 = args[0].(error)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockContextClient_ErrorResponse_Call) Return(b bool) *MockContextClient_ErrorResponse_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockContextClient_ErrorResponse_Call) RunAndReturn(run func(err error, response any) bool) *MockContextClient_ErrorResponse_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockContextClient
func (_mock *MockContextClient) Get(url string, response any) error {
	ret := _mock.Called(url, response)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, any) error); ok {
		r0 = returnFunc(url, response)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContextClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockContextClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - url string
//   - response any
func (_e *MockContextClient_Expecter) Get(url any, response any) *MockContextClient_Get_Call {
	return &MockContextClient_Get_Call{Call: _e.mock.On("Get", url, response)}
}

func (_c *MockContextClient_Get_Call) Run(run func(url string, response any)) *MockContextClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockContextClient_Get_Call) Return(err error) *MockContextClient_Get_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContextClient_Get_Call) RunAndReturn(run func(url string, response any) error) *MockContextClient_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetContext provides a mock function for the type MockContextClient
func (_mock *MockContextClient) GetContext(ctx context.Context, url string, response any) error {
	ret := _mock.Called(ctx, url, response)

	if len(ret) == 0 {
		panic("no return value specified for GetContext")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any) error); ok {
		r0 = returnFunc(ctx, url, response)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContextClient_GetContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetContext'
type MockContextClient_GetContext_Call struct {
	*mock.Call
}

// GetContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - response any
func (_e *MockContextClient_Expecter) GetContext(ctx any, url any, response any) *MockContextClient_GetContext_Call {
	return &MockContextClient_GetContext_Call{Call: _e.mock.On("GetContext", ctx, url, response)}
}

func (_c *MockContextClient_GetContext_Call) Run(run func(ctx context.Context, url string, response any)) *MockContextClient_GetContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockContextClient_GetContext_Call) Return(err error) *MockContextClient_GetContext_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContextClient_GetContext_Call) RunAndReturn(run func(ctx context.Context, url string, response any) error) *MockContextClient_GetContext_Call {
	_c.Call.Return(run)
	return _c
}

// Headers provides a mock function for the type MockContextClient
func (_mock *MockContextClient) Headers() http.Header {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Headers")
	}

	var r0 http.Header
	if returnFunc, ok := ret.Get(0).(func() http.Header); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Header)
		}
	}
	return r0
}

// MockContextClient_Headers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Headers'
type MockContextClient_Headers_Call struct {
	*mock.Call
}

// Headers is a helper method to define mock.On call
func (_e *MockContextClient_Expecter) Headers() *MockContextClient_Headers_Call {
	return &MockContextClient_Headers_Call{Call: _e.mock.On("Headers")}
}

func (_c *MockContextClient_Headers_Call) Run(run func()) *MockContextClient_Headers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContextClient_Headers_Call) Return(header http.Header) *MockContextClient_Headers_Call {
	_c.Call.Return(header)
	return _c
}

func (_c *MockContextClient_Headers_Call) RunAndReturn(run func() http.Header) *MockContextClient_Headers_Call {
	_c.Call.Return(run)
	return _c
}

// Post provides a mock function for the type MockContextClient
func (_mock *MockContextClient) Post(url string, request any, response any) error {
	ret := _mock.Called(url, request, response)

	if len(ret) == 0 {
		panic("no return value specified for Post")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, any, any) error); ok {
		r0 = returnFunc(url, request, response)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContextClient_Post_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Post'
type MockContextClient_Post_Call struct {
	*mock.Call
}

// Post is a helper method to define mock.On call
//   - url string
//   - request any
//   - response any
func (_e *MockContextClient_Expecter) Post(url any, request any, response any) *MockContextClient_Post_Call {
	return &MockContextClient_Post_Call{Call: _e.mock.On("Post", url, request, response)}
}

func (_c *MockContextClient_Post_Call) Run(run func(url string, request any, response any)) *MockContextClient_Post_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockContextClient_Post_Call) Return(err error) *MockContextClient_Post_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContextClient_Post_Call) RunAndReturn(run func(url string, request any, response any) error) *MockContextClient_Post_Call {
	_c.Call.Return(run)
	return _c
}

// PostContext provides a mock function for the type MockContextClient
func (_mock *MockContextClient) PostContext(ctx context.Context, url string, request any, response any) error {
	ret := _mock.Called(ctx, url, request, response)

	if len(ret) == 0 {
		panic("no return value specified for PostContext")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any, any) error); ok {
		r0 = returnFunc(ctx, url, request, response)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContextClient_PostContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostContext'
type MockContextClient_PostContext_Call struct {
	*mock.Call
}

// PostContext is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - request any
//   - response any
func (_e *MockContextClient_Expecter) PostContext(ctx any, url any, request any, response any) *MockContextClient_PostContext_Call {
	return &MockContextClient_PostContext_Call{Call: _e.mock.On("PostContext", ctx, url, request, response)}
}

func (_c *MockContextClient_PostContext_Call) Run(run func(ctx context.Context, url string, request any, response any)) *MockContextClient_PostContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		var arg3 any
		if args[3] != nil {
			arg3 = args[3].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockContextClient_PostContext_Call) Return(err error) *MockContextClient_PostContext_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContextClient_PostContext_Call) RunAndReturn(run func(ctx context.Context, url string, request any, response any) error) *MockContextClient_PostContext_Call {
	_c.Call.Return(run)
	return _c
}
