name: Publish Docs

on:
  workflow_dispatch: {}

permissions:
  contents: write
  actions: read

env:
  GO_VERSION: 1.24.x

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@09d2acae674a48949e3602304ab46fd20ae0c42f

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Setup Go
        uses: actions/setup-go@fa96338abe5531f6e34c5cc0bbe28c1a533d5505
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Generate Service Config Docs
        run: |
          go mod download
          go clean -cache  # Clear build cache
          ./generate-service-config-docs.sh

      - name: Setup Python
        uses: actions/setup-python@12648859835f68b273febdd9aab9972bbb624d8c
        with:
          python-version: "3.13.5"
          cache: "pip"
          cache-dependency-path: |
            docs-requirements.txt

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache

          restore-keys: |
            mkdocs-material-

      - name: Install mkdocs
        run: |
          pip install -r docs-requirements.txt

      - name: Build and Deploy
        run: mkdocs gh-deploy --force --verbose
