name: Publish Docs

on:
  workflow_dispatch: {}

permissions:
  contents: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Setup Go
        uses: actions/setup-go@78535dd5f299baffe8c7a20903d46f69f967f55b
        with:
          go-version: "1.24"

      - name: Generate Service Config Docs
        run: |
          go mod download
          go clean -cache  # Clear build cache
          ./generate-service-config-docs.sh

      - name: Setup Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: "3.13.3"
          cache: "pip"
          cache-dependency-path: |
            docs-requirements.txt

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache

          restore-keys: |
            mkdocs-material-

      - name: Install mkdocs
        run: |
          pip install -r docs-requirements.txt

      - name: Build and Deploy
        run: mkdocs gh-deploy --force --verbose
