name: Lint

on:
  workflow_call:

permissions:
  contents: read

jobs:
  lint:
    name: Run Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2

      - name: Set up Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b
        with:
          go-version: "1.24.1"

      - name: Install dependencies
        run: go mod download

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@9938e103f8065deff3f289d9e975270d5541b866
        with:
          version: v1.64.5
          args: --timeout=5m --config= # Use default linter settings

      - name: Format Go code
        run: |
          go fmt ./...

      - name: Check for uncommitted changes after formatting
        run: |
          git diff --exit-code || (echo "Detected unformatted files. Run 'go fmt' to format your code."; exit 1)
