name: Release (Production)

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch: {}

permissions:
  contents: write
  packages: write
  attestations: write
  id-token: write

jobs:
  lint:
    uses: ./.github/workflows/lint.yaml

  test:
    uses: ./.github/workflows/test.yaml

  build:
    uses: ./.github/workflows/build.yaml
    secrets: inherit
    needs:
      - test

  update-go-docs:
    uses: ./.github/workflows/update-go-docs.yaml
    needs:
      - build
