---
name: Run Security Checks
on:
  push:
    branches: [main]
    paths:
      - internal/**
      - pkg/**
      - shoutrrr/**
      - go.mod
      - go.sum
      - shoutrrr.go

env:
  OUTPUT_FILE: results.sarif

permissions:
  contents: read

jobs:
  gosec:
    name: Golang Security Checker
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - name: Checkout Source
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - name: Run Gosec Security Scanner
        uses: securego/gosec@4a3bd8af174872c778439083ded7adbf3747e770 # v2.26.1
        with:
          args: "-exclude-generated -no-fail -fmt sarif -out results.sarif ./..."
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@95e58e9a2cdfd71adc6e0353d5c52f41a045d225 # v4
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: results.sarif

  govulncheck:
    name: govulncheck
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      security-events: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: ./.github/actions/govulncheck
