name: Run tests and upload coverage

on:
  workflow_call:

permissions:
  contents: read

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2

      - name: Set up Go
        uses: actions/setup-go@c4c114188661c0fa735e5b938764519fc6e8efa9
        with:
          go-version: "1.24.1"

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: |
          go test -v -coverprofile coverage.out -covermode atomic ./...

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@3440e5ef70c638a9f44602a80ab017feee1309fe
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
